---

- hosts: all
  become: true
  pre_tasks:
    - name: updates repo for Ubuntu
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"


- hosts: web_server
  become: true
  roles:
    - web_server


