---

- hosts: all
  become: true
  tasks:

  - name: install updates (Pop!_OS)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Pop!_OS"

  - name: install update (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_server
  become: true
  tasks:
    - name: install apache2 and curl (Pop!_OS)
      apt:
        name:
          - apache2
          - curl
      state: latest
    when: ansible_distribution == "Pop!_OS"

    - name: install updates (Ubuntu)
      apt:
        name:
           - apache2
           - curl
      state: latest 
    when: ansible_distribution == "Ubuntu"
