---
- name: Install Terraform
  hosts: all
  become: yes
  tasks:
    - name: Download Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
        dest: /tmp/terraform.zip

    - name: Extract Terraform
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Ensure terraform is executable
      file:
        path: /usr/local/bin/terraform
        mode: '0755'
