- name: Install apache2, php, tmux, and mysql-server 
  tags: server_app
  apt:
    name:
      - apache2
      - php
      - mysql-server
      - nginx
      - tmux
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Start apache2 and enable apache2
  tags:  start_apache2
  service:
      name: apache2
      state: started
      enabled: yes
  notify: restart_apache2

- name: Start mysql-server
  tags: sql
  service:
    name: mysql
    state: started
    enabled: yes
  notify: restart_mysql


