- name: Add ssh key for simone
  tags: always
  authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHtQtGpMRxrzIkEex0sxfl5aGfw2svlXEeqtJjNTU5Wq ansible"

- name: generate a sshd_config file from a template
  tags: ssh_config
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_ssh
