- name: restart_apache2
  service:
      name: apache2
      state: restarted

- name: restart_mysql
  service:
    name: mysql
    state: restarted

- name: restart_nginx
  service:
    name: nginx
    state: restarted
